---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: imagestreamTemplate
  creationTimestamp:
  annotations:
    description: This template will create a single imageStream.
    tags: ''
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: build-imagestream-dest${IDENTIFIER}
  spec: {}
parameters:
- name: IDENTIFIER
  description: Number to append to the name of resources
  value: '1'
  required: true
labels:
  template: imagestreamTemplate
