provider: local
ClusterLoader:
  cleanup: True
  projects:
    - num: 100
      basename: testprojects
      ifexists: delete
      nodeselector: "node-role.kubernetes.io/worker="
      templates:
        - num: 3
          file: /root/apf_templates/build-config-template.yaml
        - num: 3
          file: /root/apf_templates/bc-imagestream-template.yaml
        - num: 6
          file: /root/apf_templates/build-template.yaml
        - num: 6
          file: /root/apf_templates/build-imagestream-template.yaml
        - num: 2
          file: /root/apf_templates/deployment-config-1rep-pause-template.yaml
          parameters:
            - ENV_VALUE: "asodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij12"
        - num: 1
          file: /root/apf_templates/deployment-config-2rep-pause-template.yaml
          parameters:
            - ENV_VALUE: "asodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij12"
        - num: 20
          file: /root/apf_templates/ssh-secret-template.yaml
        - num: 3
          file: /root/apf_templates/route-template.yaml
