{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "apps.openshift.io/v1",
            "kind": "DeploymentConfig",
            "metadata": {
                "labels": {
                    "template": "deploymentConfigTemplate"
                },
                "name": "deploymentconfig2v1"
            },
            "spec": {
                "replicas": 2,
                "selector": {
                    "name": "replicationcontroller2v1"
                },
                "strategy": {
                    "type": "Rolling"
                },
                "template": {
                    "metadata": {
                        "labels": {
                            "name": "replicationcontroller2v1"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "capabilities": {},
                                "env": [
                                    {
                                        "name": "ENVVAR1_2v_1",
                                        "value": "wBWawenSyiB1aL0uJOwrPjsUxUBB5UGIw8cIxatQntFoRKle2d7lfCNdPcpu2TEJieTCBWh1QiOFa5DolJiPt3I25hEQNiCbktx6qqhF8EVLtUSAKu4y6UiMFukhKSTh4NR7q8uOl3lcPbwOvtfvhTvAlXYHRX51nbHHBj7kAyfOAuSenB4NCGla8ptQy5n3Yw1omWV1gsr2gvgW8v8i0gaK0UKA66QjwtUgUDRL5dNMVIYHbFrA4ap4qEXucLu"
                                    },
                                    {
                                        "name": "ENVVAR2_2v_1",
                                        "value": "wBWawenSyiB1aL0uJOwrPjsUxUBB5UGIw8cIxatQntFoRKle2d7lfCNdPcpu2TEJieTCBWh1QiOFa5DolJiPt3I25hEQNiCbktx6qqhF8EVLtUSAKu4y6UiMFukhKSTh4NR7q8uOl3lcPbwOvtfvhTvAlXYHRX51nbHHBj7kAyfOAuSenB4NCGla8ptQy5n3Yw1omWV1gsr2gvgW8v8i0gaK0UKA66QjwtUgUDRL5dNMVIYHbFrA4ap4qEXucLu"
                                    }
                                ],
                                "image": "gcr.io/google-containers/pause-amd64:3.0",
                                "imagePullPolicy": "IfNotPresent",
                                "name": "pause2v1",
                                "ports": [
                                    {
                                        "containerPort": 8080,
                                        "protocol": "TCP"
                                    }
                                ],
                                "resources": {},
                                "securityContext": {
                                    "capabilities": {},
                                    "privileged": false
                                }
                            }
                        ],
                        "restartPolicy": "Always",
                        "serviceAccount": ""
                    }
                },
                "triggers": [
                    {
                        "type": "ConfigChange"
                    }
                ]
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "labels": {
                    "template": "deploymentConfigTemplate"
                },
                "name": "service2v1"
            },
            "spec": {
                "portalIP": "",
                "ports": [
                    {
                        "name": "serviceport2v1",
                        "port": 80,
                        "protocol": "TCP",
                        "targetPort": 8080
                    }
                ],
                "selector": {
                    "name": "replicationcontroller2v1"
                },
                "sessionAffinity": "None",
                "type": "ClusterIP"
            },
            "status": {
                "loadBalancer": {}
            }
        }
    ]
}
